// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';
import {library} from '../models';

export function AddPool(arg1:string):Promise<Error>;

export function CreatePool(arg1:string):Promise<Error>;

export function GetConfigTemplate():Promise<string>;

export function GetMessages(arg1:string,arg2:number,arg3:number):Promise<Array<chat.Message>>;

export function GetNick():Promise<string>;

export function GetPoolList():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ListLibrary(arg1:string):Promise<Array<library.Document>>;

export function PostMessage(arg1:string,arg2:chat.Message):Promise<Error>;
