// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPool(arg1) {
  return window['go']['main']['App']['AddPool'](arg1);
}

export function CreatePool(arg1) {
  return window['go']['main']['App']['CreatePool'](arg1);
}

export function GetConfigTemplate() {
  return window['go']['main']['App']['GetConfigTemplate']();
}

export function GetIdentities(arg1) {
  return window['go']['main']['App']['GetIdentities'](arg1);
}

export function GetMessages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3, arg4);
}

export function GetNick() {
  return window['go']['main']['App']['GetNick']();
}

export function GetPoolList() {
  return window['go']['main']['App']['GetPoolList']();
}

export function GetSelf() {
  return window['go']['main']['App']['GetSelf']();
}

export function GetToken(arg1, arg2) {
  return window['go']['main']['App']['GetToken'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListLibrary(arg1) {
  return window['go']['main']['App']['ListLibrary'](arg1);
}

export function PostMessage(arg1, arg2) {
  return window['go']['main']['App']['PostMessage'](arg1, arg2);
}

export function UpdateIdentity(arg1) {
  return window['go']['main']['App']['UpdateIdentity'](arg1);
}
